---
- hosts: localhost
  become: true

  tasks:

    - name: update apt-cache (daily)
      apt: update_cache=yes cache_valid_time=86400
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

#sudo apt-get -y upgrade

    - name: add vds key to vagrant authorized_keys file
      authorized_key:
        user: vagrant
        state: present
        key: '{{ item }}'
      with_file:
        - /boot/vds.key

    - name: add vds key to root authorized_keys file
      authorized_key:
        user: root
        state: present
        key: '{{ item }}'
      with_file:
        - /boot/vds.key

    # - name: install packages
      #sudo apt-get -y install vim ansible


